
export const TIMESHEET_FETCH_START = "TIMESHEET_FETCH_START";
export const TIMESHEET_FETCH_SUCCESS = "TIMESHEET_FETCH_SUCCESS";
export const TIMESHEET_FETCH_FAIL = "TIMESHEET_FETCH_FAIL";

export const REMAINING_DAY_FETCH_SUCCESS = " REMAINING_DAY_FETCH_SUCCESS";
export const REMAINING_DAY_FETCH_START = " REMAINING_DAY_FETCH_START";
export const REMAINING_DAY_FETCH_FAIL = " REMAINING_DAY_FETCH_FAIL";

export const UPDATE_EDIT_STATUS = "UPDATE_EDIT_STATUS";